# Generated by Django 5.0.4 on 2024-05-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ads/", verbose_name="Изображение"
            ),
        ),
    ]
